### ISSUE TITLE
[bug] yarn example android: '_BuildScript_' Unsupported class file major version 63

### ISSUE THREAD

**Issue by robert-elles** [5-stones/react-native-readium#51]
Hi,

On a clean clone of this repo I tried building the example app for android following this guide: [Example App](https://github.com/5-stones/react-native-readium/blob/main/example/README.md)

First `yarn bootstrap` and `yarn example start` work fine. But i get the following error in the next step of `yarn example android`:

```
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/home/robert/code/polyglot/react-native-main/react-native-readium/example/android/settings.gradle' (/home/robert/.gradle/caches/7.5.1/scripts/hnp36d491odjmf9trkeyzhln).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 944ms

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/home/robert/code/polyglot/react-native-main/react-native-readium/example/android/settings.gradle' (/home/robert/.gradle/caches/7.5.1/scripts/hnp36d491odjmf9trkeyzhln).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 944ms

    at makeError (/home/robert/code/polyglot/react-native-main/react-native-readium/example/node_modules/execa/index.js:174:9)
    at /home/robert/code/polyglot/react-native-main/react-native-readium/example/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/home/robert/code/polyglot/react-native-main/react-native-readium/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/home/robert/code/polyglot/react-native-main/react-native-readium/example/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by robert-elles** [comment]
I was on java 21 and needed to downgrade to 17 or 11
